# Install google-authenticator MFA for ssh on ProxMox 5.3 Hypervisor (Debian 9 Stretch)
---
- hosts: all
  tasks:
  - name: Install libpam-google-authenticator .deb
    apt: 
      state: latest
      update_cache: yes
      name: libpam-google-authenticator
  - name: Configure /etc/pam.d/sshd
    lineinfile: 
      path: /etc/pam.d/sshd
      line: 'auth required pam_google_authenticator.so'
  - name: Configure /etc/ssh/sshd_config
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
      seuser: system_u
      serole: object_r
      setype: etc_t
      backup: yes
      
