# Install and configure yum-cron for auto-update of security patches
- name: Install yum-cron package
  yum:
    state: latest
    name: yum-cron
- name: Template out /etc/yum/yum-cron.conf
  template:
    backup: yes
    src: yum-cron.conf
    dest: /etc/yum/yum-cron.conf
    owner: root
    group: root
    mode: 0644
    setype: etc_t
- name: Template out /etc/yum/yum-cron-hourly.conf
  template:
    backup: yes
    src: yum-cron-hourly.conf
    dest: /etc/yum/yum-cron-hourly.conf
    owner: root
    group: root
    mode: 0644
    setype: etc_t
